name: LeetCode Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: LeetCode submission fetch
        run: |
          python fetch_leetcode.py  # This is your fetch script

      - name: Commit changes
        run: |
          git config --global user.name "Adarshraj8"
          git config --global user.email "adarshrajgr2016@gmail.com"
          git add leetcode_submissions.txt
          git commit -m "Auto update from LeetCode submission" || echo "No changes to commit"
          git push
